"""add user_sessions table

Revocable opaque login sessions (storage foundation for ADR-P01):
- token_hash / csrf_token_hash are SHA-256 digests (BINARY(32)); raw
  credentials are never stored.
- FK ON DELETE CASCADE: sessions are ephemeral credentials, not user
  history — account deletion must not be blocked by stale sessions.
- Timeline CHECK (created_at <= last_activity_at <= absolute_expires_at)
  and revocation-shape CHECK (revoked_at <-> revocation_reason) are
  row-local and enforced by MySQL 8.4.

Revision ID: 297c92da239d
Revises: 8f0f8c585641
Create Date: 2026-09-04 13:54:52.791306+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '297c92da239d'
down_revision: Union[str, None] = '8f0f8c585641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('session_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('token_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('csrf_token_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('absolute_expires_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('revoked_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('revocation_reason', sa.String(length=50), nullable=True),
    sa.CheckConstraint('(revoked_at IS NULL AND revocation_reason IS NULL) OR (revoked_at IS NOT NULL AND revocation_reason IS NOT NULL)', name=op.f('chk_user_sessions_revocation_shape')),
    sa.CheckConstraint('last_activity_at >= created_at AND absolute_expires_at >= last_activity_at', name=op.f('chk_user_sessions_timeline')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='fk_user_sessions_user', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('token_hash', name='uq_user_sessions_token_hash')
    )
    op.create_index('idx_user_sessions_cleanup', 'user_sessions', ['absolute_expires_at', 'revoked_at'], unique=False)
    op.create_index('idx_user_sessions_user_active', 'user_sessions', ['user_id', 'revoked_at', 'absolute_expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Drop the FK before the indexes: MySQL error 1553 refuses to drop an
    # index still required by a foreign-key constraint. drop_table then
    # removes the remaining objects atomically.
    op.drop_constraint('fk_user_sessions_user', 'user_sessions', type_='foreignkey')
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
